language: python
env:
  - PYTHONPATH=./src/
python:
  - "3.6"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - conda env create -f ./src/madrl_env.yml
  - conda activate madrl_env
  - conda env update -f ./src/environments/gym_atari/madrl_gym_atari_env.yml
script:
  - pytest